"""Initial migration with labels

Revision ID: 64f700f1e692
Revises: 
Create Date: 2025-03-29 08:42:38.749701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64f700f1e692'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('technique',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('youtube_url', sa.String(length=255), nullable=False),
    sa.Column('embedded_url', sa.String(length=255), nullable=False),
    sa.Column('technique_id', sa.Integer(), nullable=False),
    sa.Column('votes', sa.JSON(), nullable=False),
    sa.Column('average_rating', sa.Float(), nullable=False),
    sa.Column('labels', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['technique_id'], ['technique.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video')
    op.drop_table('user')
    op.drop_table('technique')
    # ### end Alembic commands ###
